version: 2.1

orbs:
  node: circleci/node@5.1.0
  aws-cli: circleci/aws-cli@4.1.1
  aws-ecr: circleci/aws-ecr@9.0.1
  aws-eks: circleci/aws-eks@2.2.0
  # custom-release: tadashi0713/custom-release@0.0.1

jobs:
  deploy_eks:
    machine:
      docker_layer_caching: true
    environment:
       PIPELINE_ID: << pipeline.id >>
    steps:
      - checkout
      - aws-ecr/build_and_push_image: # AWS ECR Orb
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::660990364978:role/tadashi_oidc_fargate
          repo: tadashi-demo-release-eks-app
          tag: '${CIRCLE_SHA1}'
      - aws-eks/update-kubeconfig-with-authenticator:
          install-aws-cli: false
          install-kubectl: true
          aws-region: ap-northeast-1
          cluster-name: tadashi-cci-demo-release
      - run:
          name: Apply Kubernetes Manifest to EKS
          command: |
            sudo apt update
            sudo apt install gettext
            export CIRCLE_SHA1_SHORT=${CIRCLE_SHA1:0:8}
            envsubst < manifest/deployment.yaml | kubectl apply -f -

workflows:
  test_and_deploy: 
    jobs:
      - node/test:
          name: unit_test
          test-results-for: jest
      - node/run:
          name: lint
          npm-run: lint
      - deploy_eks:
          context:
            - aws-oidc-fargate
          filters:
            branches:
              only:
                - main
      # - custom-release/eks:
      #     aws_region: ap-northeast-1
      #     cluster_name: tadashi-cci-demo-release
      #     pipeline_id: << pipeline.id >>
      #     repo_name: tadashi-demo-release-eks-app
      #     role_arn: arn:aws:iam::660990364978:role/tadashi_oidc_fargate
      #     context:
      #       - aws-oidc-fargate
      #     filters:
      #       branches:
      #         only:
      #           - main
