version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.1
  aws-ecr: circleci/aws-ecr@9.0.1
  aws-eks: circleci/aws-eks@2.2.0

jobs:
  build_push_ecr:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - aws-ecr/build_and_push_image: # AWS ECR Orb
          auth:
            - aws-cli/setup
          repo: tadashi-demo-release-eks-app
          tag: '${CIRCLE_SHA1}'
      - aws-eks/update-kubeconfig-with-authenticator:
          install-aws-cli: false
          aws-profile: default
          install-kubectl: true
          kubectl-version: v1.28.3
          cluster-name: tadashi-demo-release-eks

workflows:
  test_and_deploy: 
    jobs:
      - build_push_ecr:
          context:
            - aws-ce
