version: 2.1

orbs:
  node: circleci/node@5.1.0
  aws-cli: circleci/aws-cli@4.1.1
  aws-ecr: circleci/aws-ecr@9.0.1
  aws-eks: circleci/aws-eks@2.2.0

jobs:
  e2e_test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.39.0-jammy
    steps:
      - checkout
      - node/install-packages
      - run: npm run test:e2e

  build_push_ecr:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - aws-ecr/build_and_push_image: # AWS ECR Orb
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::660990364978:role/tadashi_oidc_fargate
          repo: tadashi-demo-release-eks-app
          tag: '${CIRCLE_SHA1}'

  deploy_eks:
    docker:
      - image: cimg/aws:2023.09
    environment:
       PIPELINE_ID: << pipeline.id >>
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: arn:aws:iam::660990364978:role/tadashi_oidc_fargate
      - aws-eks/update-kubeconfig-with-authenticator:
          install-aws-cli: false
          aws-region: ap-northeast-1
          cluster-name: tadashi-cci-demo-release
      - run:
          command: |
            sudo apt update
            sudo apt install gettext
            export CIRCLE_SHA1_SHORT=${CIRCLE_SHA1:0:8}
            envsubst < manifest/deployment.yaml | kubectl apply -f -

workflows:
  test_and_deploy: 
    jobs:
      - node/test:
          name: unit_test
          test-results-for: jest
      - e2e_test:
          requires:
            - unit_test
      - build_push_ecr:
          context:
            - aws-oidc-fargate
          filters:
            branches:
              only:
                - main
      - deploy_eks:
          context:
            - aws-oidc-fargate
          requires:
            - build_push_ecr
