version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.1
  aws-ecr: circleci/aws-ecr@9.0.1
  aws-eks: circleci/aws-eks@2.2.0

jobs:
  build_push_ecr:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - aws-ecr/build_and_push_image: # AWS ECR Orb
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::660990364978:role/tadashi_oidc_fargate
          repo: tadashi-demo-release-eks-app
          tag: '${CIRCLE_SHA1}'

  deploy_eks:
    docker:
      - image: cimg/aws:2023.09
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: arn:aws:iam::660990364978:role/tadashi_oidc_fargate
      - aws-eks/update-kubeconfig-with-authenticator:
          install-aws-cli: false
          aws-region: ap-northeast-1
          cluster-name: tadashi-cci-demo-release
      - run: kubectl get po

workflows:
  test_and_deploy: 
    jobs:
      - build_push_ecr:
          context:
            - aws-oidc-fargate
      - deploy_eks:
          context:
            - aws-oidc-fargate
