version: 2.1

orbs:
  node: circleci/node@5.2.0
  aws-cli: circleci/aws-cli@4.1.3
  aws-ecr: circleci/aws-ecr@9.0.4
  aws-eks: circleci/aws-eks@2.2.0

jobs:
  e2e_test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.39.0-focal
    steps:
      - checkout
      - node/install-packages
      - run: | 
          TESTFILES=$(circleci tests glob "e2e/*.spec.ts")
          echo $TESTFILES | circleci tests run --command="xargs npx playwright test" --verbose
      - store_test_results:
          path: results.xml

  e2e_test_parallel:
    parallelism: 10 # Parallelism
    docker:
      - image: mcr.microsoft.com/playwright:v1.39.0-focal
    steps:
      - checkout
      - node/install-packages
      - run: | 
          TESTFILES=$(circleci tests glob "e2e/*.spec.ts")
          echo $TESTFILES | circleci tests run --command="xargs npx playwright test" --verbose --split-by=timings
      - store_test_results:
          path: results.xml

  deploy_eks:
    machine:
      docker_layer_caching: true
    environment:
       PIPELINE_ID: << pipeline.id >>
    steps:
      - checkout
      - aws-ecr/build_and_push_image: # AWS ECR Orb
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::660990364978:role/tadashi_oidc_fargate
          repo: tadashi-demo-release-eks-app
          tag: '${CIRCLE_SHA1}'
      - aws-eks/update-kubeconfig-with-authenticator:
          install-aws-cli: false
          install-kubectl: true
          aws-region: ap-northeast-1
          cluster-name: tadashi-cci-demo-release
      - run:
          name: Apply Kubernetes Manifest to EKS
          command: |
            sudo apt update
            sudo apt install gettext
            export CIRCLE_SHA1_SHORT=${CIRCLE_SHA1:0:8}
            envsubst < manifest/rollout.yaml | kubectl apply -f -

workflows:
  test_and_deploy: 
    jobs:
      - node/test:
          name: unit_test
          test-results-for: jest
      - e2e_test:
          requires:
            - unit_test
      - e2e_test_parallel:
          requires:
            - unit_test
      - deploy_eks:
          context:
            - aws-oidc-fargate
          filters:
            branches:
              only:
                - main
