version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.1
  aws-ecr: circleci/aws-ecr@9.0.1

jobs:
  build_push_ecr:
    machine:
      docker_layer_caching: true
      image: ubuntu-2004:current
    steps:
      - checkout
      - aws-ecr/build_and_push_image: # AWS ECR Orb
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::660990364978:role/tadashi_oidc_fargate
          repo: tadashi-graviton-fargate-demo
          tag: '${CIRCLE_SHA1}'

workflows:
  test_and_deploy: 
    jobs:
      - build_push_ecr:
          context:
            - aws-oidc-fargate
