apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: demo-app
  newName: 660990364978.dkr.ecr.ap-northeast-1.amazonaws.com/tadashi-demo-release-eks-app
  newTag: 8e12dc7015e470fe7f5671f010d1dcfea19d0981
