apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    circleci.com/job-number: "${CIRCLE_BUILD_NUM}"
    circleci.com/pipeline-id: "${CIRCLE_PIPELINE_ID}"
    circleci.com/project-id: "${CIRCLE_PROJECT_ID}"
    circleci.com/workflow-id: "${CIRCLE_WORKFLOW_ID}"
  labels:
    app: demo-app
    circleci.com/component-name: demo-app
    circleci.com/version: "${CIRCLE_SHA1_SHORT}"
  name: demo-app
spec:
  replicas: 4
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause: {}
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
        circleci.com/component-name: demo-app
        circleci.com/version: "${CIRCLE_SHA1_SHORT}"
    spec:
      containers:
        - image: 660990364978.dkr.ecr.ap-northeast-1.amazonaws.com/tadashi-demo-release-eks-app:$CIRCLE_SHA1
          name: demo-app
          ports:
            - containerPort: 3000
